### ISSUE TITLE
Add keep_expanding_json_column option

### ISSUE THREAD

**Issue by muga** [civitaspo/embulk-filter-expand_json#18]
As the default behavior of this plugin, it removes a column specified as `json_column_name` option from input schema, but I sometimes want to keep the value of the column in the case that the column is schemaless Json value.

For example, 

```
filters:
- type: expand_json
  json_column_name: record
  root: ''
  expanded_columns:
  - {name: "$.['e0']", type: string}
  - {name: "$.['e1']", type: string}
```

As the above config given, this filter generates new columns `e0:string` and `e1:string` in the output schema. And it removes the `record` column from the schema. But, even though the `record` column has other keys like `e2` and `e3` (since `record` is Json value), those keys and values are removed. We don't know if new keys will be added in the value or not in the future.

`keep_expanding_json_column` flag allows users to keep the specified column in the output schema, if  the value is true. The flag is false by default to avoid braking the backward compatibility.

@civitaspo how about this flag option? If you agree, I will implement this option.
