### ISSUE TITLE
Undocumented time_zone option

### ISSUE THREAD

**Issue by muga** [civitaspo/embulk-filter-expand_json#26]
According to the source code, the plugin has "time_zone" option but, it is undocumented in README.md. Do you have any reasons? If you don't have, I will document. (If the option is still experimental and you still find better option, I want to suggest column-based timezone setting like following.)

```yaml
- type: expand_json
  json_column_name: record
  expanded_columns:
  - {name: time, type: timestamp, format: "%Y-%m-%d %H:%M:%S", timezone: Asia/Tokyo}
  ... ...
```
